### ISSUE TITLE
full width doesn't work if returned ruler width value is 0

### ISSUE THREAD

**Issue by orouz** [guywald1/vscode-prismo#4]
was totally sold on the full width section thing when i saw the screenshot

didn't work out of the box though, the ruler width was zero so the math was off. 
looked into it and saw you're returning the first value from the ruler positions array 
i changed it to make sure the value is not zero, opened a pr #3

**Comment by guywaldman** [comment]
You're right, didn't assume it could be zero. Merging 👍
